### ISSUE TITLE
Error in rendering pydata theme

### ISSUE THREAD

**Issue by AdamRJensen** [sphinx-themes/sphinx-themes.org#109] opened 2022-09-30 14:45 UTC
The pydata theme is currently not rendering correctly:
![image](https://user-images.githubusercontent.com/39184289/193295632-70b1d2bf-b71c-4e30-a374-3d0b4196de23.png)

![image](https://user-images.githubusercontent.com/39184289/193295672-23133649-b8b6-417a-be3a-a7c6b1c27946.png)

**Comment by pradyunsg** [comment] 2022-09-30 15:34
Duplicate of https://github.com/sphinx-themes/sphinx-themes.org/issues/105 -- this is a regression in the theme, not this site.

See https://github.com/pydata/pydata-sphinx-theme/issues/913, which hasn't been released yet.

**Closed by pradyunsg** 2022-09-30 15:34 UTC
