### ISSUE TITLE
Lots of themes fail with `'style' is undefined` since Sphinx 7.0.0's release

### ISSUE THREAD

**Issue by vwheeler63** [sphinx-themes/sphinx-themes.org#156] opened 2024-09-05 21:03 UTC
Hello.  As I write this it is about 21:00 GMT (15:00 Mountain Daylight Time).  About 24-28 hours ago, all of the themes at  https://sphinx-themes.org  were displaying correctly.  However, today I went to look at the list more thoroughly to build some documentation about them for potential future use, and quite a few of them are not displaying correctly.  I captured the exception message on attempting to display the `hachibee` theme.  It is below.  I hope this is both helpful and timely.  Hopefully whatever is causing this one not to display is in common with the others.  Probably 50-60% of them WERE displaying correctly.

```
======================================== stderr ========================================
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/urllib/parse.py:docstring of urllib.parse.quote:13: ERROR: Unexpected indentation. [docutils]
/home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/kitchen-sink/blocks.rst:138: WARNING: Include file '/home/runner/work/sphinx-themes.org/src/furo/__init__.py' not found or reading it failed [docutils]
/home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/kitchen-sink/lists.rst:202: WARNING: Include file '/home/runner/work/sphinx-themes.org/src/furo/__init__.py' not found or reading it failed [docutils]

Traceback (most recent call last):
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1160, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/jinja2glue.py", line 201, in render
    return self.environment.get_template(template).render(context)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/hachibee_sphinx_theme/hachibee/page.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/hachibee_sphinx_theme/hachibee/layout.html", line 134, in top-level template code
    {{ css() }}
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/hachibee_sphinx_theme/hachibee/layout.html", line 95, in template
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
jinja2.exceptions.UndefinedError: 'style' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 366, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 613, in write
    self._write_serial(sorted(docnames))
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 623, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 675, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/runner/work/sphinx-themes.org/sphinx-themes.org/build/hachibee-sphinx-theme/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1167, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page index.
Reason: UndefinedError("'style' is undefined")

Theme error:
An error happened in rendering the page index.
Reason: UndefinedError("'style' is undefined")
```

Kind regards,
Vic

**Comment by pradyunsg** [comment] 2024-09-05 21:49
The issue is that those themes are not compatible with the latest version of Sphinx and, fundamentally, `pip install <that theme package>` will result in a failing build with that exact message.

This is not a problem with this site but rather a problem with those projects.

**Comment by pradyunsg** [comment] 2024-09-05 21:52
I'm gonna go ahead and close this as something that we can't really fix, but I'll also pin this for visibility for the next person who comes wondering about this.

**Closed by pradyunsg** 2024-09-05 21:52 UTC

**Comment by vwheeler63** [comment] 2024-09-06 00:25
> This is not a problem with this site but rather a problem with those projects.

Ah!  Thanks for the clarification!  Hopefully the authors will fix them in a hurry!  :-)

**Comment by roccomoretti** [comment] 2026-08-18 22:04
Given that it's close to two years later, and it looks like a large number of themes are still in a broken state, I'd probably recommend curating https://sphinx-themes.org/ for the themes which actually are kept up-to-date. (If you don't want to get rid of them entirely, perhaps by moving them to something like a "historical styles" or "v6-and-before" subsection.)

It's not a very beginner-friendly look for someone starting with Sphinx to go to the recommended theme picking site (e.g. from the Sphinx documentation at https://www.sphinx-doc.org/en/master/tutorial/more-sphinx-customization.html) and then be confronted with a third of the themes being broken. It makes it look like no one cares, and that the site is janky link-rot. (Which I don't think it actually is.)
